# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "GifpJ8oE0Un1hJIG4KqUF6yWunCUxBLVlwPIWs62MXw151zYKeh68ouARHdtv8dohjiqIa6crD4F3ZFwdB6HCoAjOPInfeEsucjS03BBY3c1B/zt4+HyTMVLxAwWp0yxlzu1YdjjzcW73QvIDmehjMyJN1GVVaHTdPVFpGM1zPipUKkKDYkaYTBH3iutW9KKm3fkNyKI1FnN0gKZye95OzSmERqRLa4l8wQ9/FbTl1xHgIqW0DeZXyIxU2hNyv+8MhLiPnqMU2Y3x/INPQhrBE7b/LnZjZoOgdgdJMYmQPs3/UGmX6HqkD+7ZwY5KvUes5nVjeiLLuf/bJOSPOSsHPidnUkwJMDHUtmS5tptwInWezLYrV6IucXnrtxMrBISEPub28ecQHi+RSwBClCSxdd4veJDAHrm76f5UYx9tdN8drVsxZdzjieNTmj3axddGkN6r9oT8AZ8cK0AiHulS9rZNW6FyUbE/+IU09YhNASAInfZUEQnHiL/g9By0XC0hPNdCXHC3fcsTDCpb1BWaDKa219pzsqry5Dr6gLH38dGZhTOBA4uGHf/O6gGRLw/M1AC7J3LXd+NefSQuLQahZNkQHNjGb8tbYPFTL/0TbXGJ1P0gHQoktACoIvLxCgQ10RlQz2DX5IlPK1bdXycuk1TxqnVgYKclaXtYuunHNc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
