travis:
  secure:
    BINSTAR_TOKEN: GifpJ8oE0Un1hJIG4KqUF6yWunCUxBLVlwPIWs62MXw151zYKeh68ouARHdtv8dohjiqIa6crD4F3ZFwdB6HCoAjOPInfeEsucjS03BBY3c1B/zt4+HyTMVLxAwWp0yxlzu1YdjjzcW73QvIDmehjMyJN1GVVaHTdPVFpGM1zPipUKkKDYkaYTBH3iutW9KKm3fkNyKI1FnN0gKZye95OzSmERqRLa4l8wQ9/FbTl1xHgIqW0DeZXyIxU2hNyv+8MhLiPnqMU2Y3x/INPQhrBE7b/LnZjZoOgdgdJMYmQPs3/UGmX6HqkD+7ZwY5KvUes5nVjeiLLuf/bJOSPOSsHPidnUkwJMDHUtmS5tptwInWezLYrV6IucXnrtxMrBISEPub28ecQHi+RSwBClCSxdd4veJDAHrm76f5UYx9tdN8drVsxZdzjieNTmj3axddGkN6r9oT8AZ8cK0AiHulS9rZNW6FyUbE/+IU09YhNASAInfZUEQnHiL/g9By0XC0hPNdCXHC3fcsTDCpb1BWaDKa219pzsqry5Dr6gLH38dGZhTOBA4uGHf/O6gGRLw/M1AC7J3LXd+NefSQuLQahZNkQHNjGb8tbYPFTL/0TbXGJ1P0gHQoktACoIvLxCgQ10RlQz2DX5IlPK1bdXycuk1TxqnVgYKclaXtYuunHNc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
