travis:
  secure:
    BINSTAR_TOKEN: nXcLIutGmdvrBRGwpV5oXsjun+UpAhqdBZqsOUCnuUquHGS3Vsd7ieL53XqDypxMTF9kAmI5fSRnPJCz8fU3c/D8JsYIQmxV0SshEG+7JfHxde0AEKVda+hkKVGBRVRM80BeIsgyjC/oUGolRqrjVHZZoz2MchTr5XvMZsyr8tcIj9Y6uTpvG2zaI40Qn8XzHGcbWhynn7/TpMVkfNn5L3rIvWpI070h71a5+2f2tVX8Ov78EeLkGbIDGaz8XdNBLql4Y046hw9/R86klIeBbL/2Gma82SZyKwuqz7emqb44i1opNDj7ogcPHtFU906z81FnC7cjEfjef3ioH1FJq1MIkFi5VdAHTF/TAm4tM4OE7LvpdD3k33Tj6AYJ34r1Jlz0t+ryRYaI+FYByGi3ctV40hJpu7oOm7vhol898AE4ttnYyCjzf+NzLRsEBFkHwEkj9h3cxAgw/x9FWR2g9YL30KsgBsXoSgtR07THvuDEhbXRcybIZoqSSGTF+yPKngv8Md02prr39guMuv1zmEaX9VOz33bwRtoMq+xAy7794iedSZVPwrDFUfe4xh+oDh2LtGwrG8SRCabAfJ3aNj0Qi5T9P13xstmA7i640/kIerMu1ioK4LSEiIBWv3iVICE0bQKEX9vZmqeWMSRetsyALUxUwi/tu38IW94A6Oo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
