travis:
  secure:
    BINSTAR_TOKEN: G3ld2ZJD3oB7a0+kDv5QSGp8WgAIcVCqeCjAtrSo9w5aYrQVT7SBRv0PxEBfXhicSKUJcDmfa7AQxDlRAM4OOESSXfMbpQcqDTD75LT/L4+l7rQOs/H3m2zo9i3pXpK+LRDTdKN/8HuWhFgSWzCE6I71xhplinTzNRk7OP+TXHmFb0hV8FgWQYwhCoF4lhYYXDgF4OwK6feSqFKHUiZVlsPleC2vUYJz06m9KMkpkldjyAGvO4u1cxj+Sb1lkew1UByJ8Cc+nH8H9qp/UimRQWCU6GWe2KErVCH2VTeIySfZ9rtvnDffTOBo8qDtahyvoAw3RD2Yjpd7mICf+fEWtSfb6XvLjE5/Cm18B2vFlWrVe187gxM0oN8F0K4GBW3r87bWzJd24DuTC6ouPpovY8oGt7Wn5mYegxLsbqbe5bkSFtOO2NlFPlnyd1hFj58SrfwjNYrvFoCFPXxNaGaSAHGemyMWPpG/Zv3ux8Zc/JwLctW25LeBMBKdRGezRIXbIxkBVQ/hqx9hglvSlL1xJHN0uucC+V/Jlfa77ReQBO83jV8HPLkzbNcIIH+bVm4pEpFKvuCuHadLC1XKqcle1DpOv6Z6tZy/QpY8K//xx/+McJACe+kSR5xLBsiiYirFdfWKYdiWOFQ3+p4S9xnd5nHaUB6mVS2q8Lj2iXKhHB4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
